version: 0.0
os: linux

files:
  - source: /dist
    destination: /var/www/country/deploy
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user

  BeforeInstall:
    - location: scripts/clean_old_files.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
