version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Ensure Amazon Linux 2 EC2 also uses Node.js 18
    commands:
      - echo "Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building the React App using Vite..."
      - npm run build

  post_build:
    commands:
      - echo "Preparing deployment artifacts..."
      - mkdir -p deploy
      - cp -r dist/* deploy/
      - echo "Build process complete."

artifacts:
  files:
    - appspec.yml
    - scripts/**
    - deploy/**  # Upload the built files for CodeDeploy to push to EC2
