version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Updating system and installing dependencies..."
      - yum update -y
      - yum install -y gcc-c++ make
      - npm install
  build:
    commands:
      - echo "Building the Vite app..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  base-directory: dist